version: '3.3'

volumes:
  kickstarterDataDB:
    external: false


services:
  kickstarter-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kickstarter
    volumes:
      - kickstarterDataDB:/var/lib/postgresql/data
    ports:
      - "5432:5432"
